name: Daily Fetch

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        
    - name: Initialize Go module
      run: go mod init main

    - name: Run Go script
      run: go run fetch_crypto.go

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add all_crypto.json
        timestamp=$(date -u)
        git commit -m "Update all_crypto.json - $timestamp"
        git push "https://${GH_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref }}